query getUsers(
$pageSize: Int,
$pageNumber: Int,
$sortBy: String!,
$sortDirection: SortDirection!,
$searchTerm: String!,
$statusFilter: UserBlockStatus!
) {
    getUsers(
        pageSize: $pageSize,
        pageNumber: $pageNumber,
        sortBy: $sortBy,
        sortDirection: $sortDirection,
        searchTerm: $searchTerm,
        statusFilter: $statusFilter
    ) {
        users {
            id
            email
            userName
            profile {
                id
                avatars {
                    url
                }
                createdAt
            }
            createdAt
            userBan {
                reason
                createdAt
            }
        }
        pagination{
            page
            pagesCount
            pageSize
            totalCount

        }
    }
}

